name: Tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: Setup VS Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build C DLLs
      run: |
        call compile_c_models.bat
      shell: cmd

    - name: Build fortran DLLs
      run: call compile_fortran_models.bat
      shell: cmd

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: pytest tests

    - name: Upload C libraries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled_c_dlls_windows
        path: .\c_models\**\*.dll

    - name: Upload fortran libraries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled_fortran_dlls_windows
        path: .\fortran_models\**\*.dll

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build C libraries
      run: |
        make
      shell: bash

    - name: Build fortran libraries
      run: |
        bash compile_fortran_models.sh
      shell: bash

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: pytest tests

    - name: Upload C libraries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled_c_libs_linux
        path: ./build_C/lib/*.so

    - name: Upload fortran libraries as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled_fortran_libs_linux
        path: ./build_Fortran/lib/*.so

