name: Tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        python-version: ['3.11']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - name: Setup VS Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build C DLLs
      run: |
        call compile_c_models.bat
      shell: cmd

    - name: Build fortran DLLs with gfortran
      run: call compile_fortran_models.bat
      shell: cmd

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest tests

    - name: Upload c DLLs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled_c_dlls
        path: .\c_models\**\*.dll

    - name: Upload fortran DLLs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled_fortran_dlls
        path: .\fortran_models\**\*.dll

