name: Tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        python-version: [' 3.10', '3.11', '3.12']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: set up visual studio build tools
      if: startsWith(runner.os, 'Windows')
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 2022

    - name: build c dlls

      if: startsWith(runner.os, 'Windows')
      shell: cmd
      run: call cd c_models/linear_elastic_with_vertical_tens_cutoff && call compile.bat && cd ../..

#    - name: Upload DLL artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: linear_elastic_dll
#        path: c_models/linear_elastic_with_vertical_tens_cutoff/linear_elastic_with_vertical_tens_cutoff.dll




#      run: call c_models/linear_elastic_with_vertical_tens_cutoff/compile.bat


#    - name: Install libGLU library on Ubuntu
#      run: |
#            if [ "$RUNNER_OS" == "Linux" ]; then
#                sudo apt-get install -y libglu1-mesa
#            fi
#      shell: bash
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest tests

